#line 2 "trafgen/trafgen_lexer.yy.c"

#line 4 "trafgen/trafgen_lexer.yy.c"

#define  YY_INT_ALIGNED long int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 39
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 110
#define YY_END_OF_BUFFER 111
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int32_t yy_accept[329] =
    {   0,
       96,   96,  111,  109,   96,   94,   96,  109,   98,   79,
       80,  109,   87,   88,   77,   76,   91,   75,   78,  100,
      100,  100,   92,  108,   82,   93,   83,  103,  103,  103,
      103,  103,  103,  103,  103,  103,  103,  103,  103,  103,
      103,  103,  103,  103,  103,  103,  103,   89,   90,   84,
       85,   81,   86,   96,   96,   79,   80,   77,   76,   75,
       78,   82,   83,   84,   81,    0,   98,   79,   80,    0,
        0,   77,   76,   75,   78,    0,    0,  101,    0,    0,
        0,    0,  100,    0,   31,  108,   82,   83,    0,    0,
        0,  102,    0,    0,    0,   18,    0,    0,    0,    0,

        0,   23,    0,    0,   52,    0,    0,   55,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   48,    0,    0,
        0,   53,   38,    0,    0,    0,    0,    0,    0,    0,
       24,    0,    0,    0,    0,   54,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       99,   84,   81,   95,  107,    0,    0,    0,    0,    0,
       30,   62,   71,    0,   19,   20,   21,   29,    0,    1,
        0,   59,    0,    0,   29,    0,    0,    0,    0,    0,
       60,   45,   69,    0,   66,    0,    0,    0,    0,   41,
       72,    0,   47,    0,   28,    0,   63,    0,    0,   36,

        3,   64,    0,   56,   32,   33,    0,   33,    0,   65,
       27,   74,   34,   35,    0,   46,   35,    0,   43,    0,
       73,   61,   42,    0,   67,    0,   97,    0,    0,    0,
       57,    0,   51,    0,   15,   14,   58,    0,   13,   44,
        2,    0,   50,   58,    0,    0,   38,   22,    0,    0,
        0,    0,    0,    0,   32,    0,   34,   26,   25,    0,
        0,   70,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   23,   55,   49,   39,    0,   22,   40,   37,
        0,   24,    0,    0,   54,    0,    0,    0,  106,    0,
        0,   57,    0,    0,    0,   18,    4,    0,    5,    0,

        0,   47,    0,   17,   16,   68,    0,   67,  105,    0,
       19,   20,   21,    0,    6,   10,    9,   36,   42,    0,
        7,   12,   11,    0,    8,    0,  104,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   24,   23,   25,   23,   26,   27,   28,
       29,   30,    1,    1,   31,   32,   33,   34,   35,   36,
       37,   38,   39,   40,   41,   42,   43,   44,   45,   46,
       47,   48,   49,   50,   51,   52,   53,   54,   55,   40,
       56,   57,   58,   59,    1,    1,   60,   32,   61,   62,

       63,   64,   65,   66,   67,   40,   68,   69,   70,   71,
       72,   73,   74,   75,   76,   77,   78,   79,   80,   81,
       82,   40,   83,   84,   85,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[86] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    4,    4,    4,
        4,    4,    4,    4,    4,    5,    1,    1,    1,    1,
        4,    4,    4,    4,    4,    4,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    5,    5,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    4,
        4,    4,    4,    4,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    5,    5,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_base[343] =
    {   0,
        0,    0,  752,  777,   84,   87,   90,    0,    0,  742,
      730,  675,  777,  777,  723,  722,  777,  720,   92,  159,
      225,   64,  777,    0,  719,  777,  698,   80,   82,  282,
      345,  126,   98,  777,   73,  162,   64,   83,   63,  156,
       90,  391,  441,  154,   91,   96,    0,  777,  777,  663,
      777,  662,  777,  166,    0,  658,  649,  641,  611,  601,
      599,  598,  596,  594,  554,  549,    0,  546,  539,  494,
      153,  497,  496,  495,  493,  482,  244,  198,    0,  103,
        0,    0,  179,  180,  777,    0,  449,  446,  252,  163,
      108,    0,  256,  258,  193,  133,  272,  183,  204,  232,

      244,  163,  260,  290,  247,  254,  248,  276,  282,  299,
      312,  334,  317,  141,  342,  347,  319,  777,  345,  363,
      348,  777,  360,  351,  353,  361,  349,  386,  377,  363,
      394,  388,  405,  395,  407,  418,  399,  409,  421,  398,
      435,  396,  438,  441,  439,  442,  410,  441,  461,  449,
        0,  399,  392,  777,  777,    0,  339,  333,  506,  323,
      469,  457,  777,  462,  482,  484,  499,  777,  488,  777,
      495,  777,  501,  506,  777,  508,  506,  496,  512,  502,
      515,  777,  777,  509,  777,  515,  516,  511,  510,  777,
      777,  319,  520,  511,  777,  510,  777,  515,  524,  521,

      777,  777,  539,  545,  777,  777,  543,  777,  541,  777,
      777,  777,  777,  777,  557,  777,  777,  557,  777,  557,
      777,  548,  546,  552,  563,    0,  777,  608,    0,  571,
      777,  558,  598,  576,  577,  777,  777,  559,  777,  777,
      777,  564,  777,  777,  579,  591,  777,  598,  609,  591,
      615,  599,  617,  610,  777,  605,  777,  777,  777,  606,
      618,  777,  614,  331,  671,  312,  614,  639,  313,  638,
      636,  643,  777,  777,  777,  777,  641,  777,  777,  777,
      649,  777,  667,  668,  777,  655,  659,  653,  777,  694,
        0,  777,  312,  314,  311,  777,  777,  665,  308,  663,

      664,  777,  670,  777,  777,  777,  677,  777,  720,  271,
      777,  777,  777,  676,  777,  272,  249,  777,  777,    0,
      216,  777,  777,  211,  777,    0,    0,  777,  749,  754,
      759,  764,  766,  214,  771,  182,  160,  144,  128,  110,
      108,  106
    } ;

static yyconst flex_int32_t yy_def[343] =
    {   0,
      328,    1,  328,  328,  328,  328,  328,  329,  330,  328,
      328,  331,  328,  328,  328,  328,  328,  328,  328,  328,
      328,   21,  328,  332,  328,  328,  328,  333,  333,  328,
      328,   29,   29,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  334,  328,  328,  328,
      328,  328,  328,  328,    7,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  329,  330,  328,  328,  328,
      328,  328,  328,  328,  328,  335,  328,   20,  336,   29,
       29,  334,   21,   29,  328,  332,  328,  328,   29,  328,
      328,   29,   29,   29,   29,   29,   29,  328,  328,  328,

      328,   84,   84,   84,   84,  328,  328,  328,  328,  328,
      103,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      334,  328,  328,  328,  328,  337,  335,  335,  328,  336,
      103,  328,  328,  328,  103,  103,  103,  328,  328,  328,
      328,  328,   84,   84,  328,  328,  328,  328,  328,  328,
       84,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,

      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  338,  328,  328,  339,  328,
      328,  328,  328,   84,   84,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  339,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      340,  328,  328,  328,  328,  328,  328,  328,  328,  328,

      328,  328,  328,  328,  328,  328,  328,  328,  328,  340,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  341,
      328,  328,  328,  341,  328,  342,  342,    0,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328
    } ;

static yyconst flex_int32_t yy_nxt[863] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,    4,   19,   20,   21,   22,
       22,   22,   22,   22,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   33,   34,   35,   36,   34,
       34,   37,   38,   34,   39,   40,   34,   41,   42,   43,
       44,   45,   46,   47,   34,   48,    4,   49,   50,   28,
       30,   31,   32,   33,   34,   35,   36,   34,   37,   38,
       34,   39,   40,   34,   41,   42,   43,   44,   45,   46,
       47,   34,   51,   52,   53,   54,   54,   54,   54,   54,
       54,   54,   54,   55,   80,   75,   56,   57,  121,   92,

       92,   58,   59,   76,   60,   79,   61,   79,  123,  327,
      328,  324,   89,  310,  116,   80,   80,   62,  122,   63,
       80,   80,  117,   80,  128,  148,  121,   90,   91,  328,
      328,  266,  149,  129,  150,  123,  113,  328,  130,  114,
       89,  116,  164,   80,   80,  115,  122,  264,   64,  117,
       80,   80,  128,  148,   90,   91,  328,  328,  111,  149,
      129,  155,  150,  226,  113,  130,  114,   54,   54,   54,
      164,  186,  115,   65,   77,  112,   78,   78,   78,   78,
       78,   78,   78,   78,   79,  160,  111,  146,  124,   80,
       81,   80,   80,   80,   80,  118,  173,   80,   80,  119,

      186,  147,  112,  125,  126,  127,  156,  120,  163,   80,
       80,   80,   82,  161,  167,  146,  124,  151,   80,   80,
       80,   80,   80,  118,  173,  328,  169,  119,  147,   80,
      125,  126,  127,  156,  120,  163,  326,  325,   80,   82,
       77,  161,   83,   83,   83,   83,   83,   83,   83,   83,
       79,  328,  328,  169,  170,   84,   80,   80,   80,   80,
       80,  159,  159,  159,  159,  159,  159,  159,  159,   80,
       80,   85,  323,   80,   80,   80,   80,  166,  328,  165,
       80,  170,  171,  177,   84,   80,   80,   80,   80,   80,
       80,  172,  162,   80,  174,  322,  320,  176,   85,   80,

       93,   80,   94,   80,   80,   95,   96,   79,   80,  171,
      168,  177,   80,   80,   80,   80,   80,   97,  172,  162,
      178,   80,  174,   80,  176,  179,   98,   99,  175,  315,
      100,  180,  313,  312,  101,  311,  297,  291,  168,  289,
      191,   80,   80,   80,   80,   97,  181,  178,  229,  227,
      158,   80,  179,   98,   99,  182,  175,  100,  184,  180,
      185,  101,   80,   80,   80,   80,   80,   80,   80,   80,
       79,  183,  187,  189,  181,  102,   80,   80,  103,  104,
      105,  188,  182,  106,  191,  184,  190,  185,  145,  107,
      108,  193,  109,  110,  194,  153,  195,  196,  197,  183,

      189,  187,  152,  198,  102,   80,  103,  104,  105,  188,
      201,  106,  202,  190,  192,  145,  107,  108,  193,  109,
      110,  131,  194,  195,  196,  132,  197,  203,  133,  134,
      198,  199,  200,  135,  204,  205,  136,  207,  201,  202,
      206,  192,  210,  214,  216,  137,  222,  211,  208,   88,
      131,  213,   87,  132,  212,  203,  133,  134,  199,  200,
      135,  204,  209,  136,  205,  215,  207,  206,  217,  210,
      214,  216,  137,  138,  222,  211,  218,  208,  139,  140,
      213,  212,  219,  141,  220,  142,  143,  221,  223,  209,
      144,  224,  225,  158,  215,  145,   75,  217,   74,   73,

       72,  138,  155,   80,  218,  230,  139,  140,  231,  219,
      141,  220,  142,  143,  221,  223,   80,  144,   80,  225,
      224,  228,  145,  159,  159,  159,  159,  159,  159,  159,
      159,   80,  230,   80,  234,  231,  232,  233,  235,   80,
      236,  237,   69,  238,   80,  239,   80,  240,   80,   68,
      241,  242,  243,  154,  244,  245,  246,  153,  247,  248,
      249,   80,  234,  232,  233,  250,  235,   80,  236,  237,
      238,  251,  252,  239,  240,  255,   80,  241,  253,  242,
      243,  244,  245,  254,  246,  247,  248,  249,  256,  257,
      258,  259,  250,  260,  261,  262,  263,  152,  251,   88,

      252,   87,   75,  255,   74,  267,  253,  268,  274,   80,
       80,  254,  275,  276,   73,  256,  269,  257,  258,  259,
      260,  261,  262,  273,  263,  265,  265,  265,  265,  265,
      265,  265,  265,  267,  268,  274,  270,   80,   80,  275,
      277,  276,  278,  279,   72,  280,  282,  271,  272,  281,
      273,  283,   69,  284,  285,  286,  287,  293,  288,  294,
      292,   68,  295,  296,  270,  153,  152,  277,  300,  278,
      298,  279,  280,  282,  271,  272,  301,  281,  302,  283,
      284,  285,  286,  299,  287,  288,  290,  292,  265,  265,
      265,  265,  265,  265,  265,  265,  300,  303,  298,  304,

      305,   88,  306,  307,  301,  308,  302,  314,  316,  317,
      299,  309,  309,  309,  309,  309,  309,  309,  309,  318,
      319,  321,   87,   74,  303,   73,   72,  304,  305,  306,
      307,   71,  308,   69,  314,  316,  317,  309,  309,  309,
      309,  309,  309,  309,  309,   68,  318,  319,  321,   66,
       66,  328,   66,   66,   67,  328,   67,   67,   67,   70,
      328,   70,   70,   70,   86,  328,   86,   86,   86,   80,
       80,  157,  157,  157,  157,  157,    3,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,

      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328
    } ;

static yyconst flex_int32_t yy_chk[863] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    5,    5,    5,    6,    6,
        6,    7,    7,    7,   22,   19,    7,    7,   37,   29,

       29,    7,    7,   19,    7,   28,    7,   29,   39,  342,
       22,  341,   28,  340,   35,   33,   33,    7,   38,    7,
       80,   80,   35,   22,   41,   45,   37,   28,   28,   29,
       29,  339,   45,   41,   46,   39,   33,   22,   41,   33,
       28,   35,   91,   32,   32,   33,   38,  338,    7,   35,
       96,   96,   41,   45,   28,   28,   29,   29,   32,   45,
       41,   71,   46,  337,   33,   41,   33,   54,   54,   54,
       91,  114,   33,    7,   20,   32,   20,   20,   20,   20,
       20,   20,   20,   20,   20,  336,   32,   44,   40,   20,
       20,   20,   20,   20,   20,   36,  102,   84,   84,   36,

      114,   44,   32,   40,   40,   40,   71,   36,   90,   83,
       95,   95,   20,   84,   95,   44,   40,  334,   20,   20,
       20,   20,   20,   36,  102,   83,   98,   36,   44,   78,
       40,   40,   40,   71,   36,   90,  324,  321,   83,   20,
       21,   84,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   78,   83,   98,   99,   21,   21,   21,   21,   21,
       21,   77,   77,   77,   77,   77,   77,   77,   77,   89,
       89,   21,  317,   93,   93,   94,   94,   94,   78,   93,
      105,   99,  100,  107,   21,   21,   21,   21,   21,   97,
       97,  101,   89,  103,  103,  316,  310,  106,   21,   30,

       30,   30,   30,   30,   30,   30,   30,   30,  105,  100,
       97,  107,   30,   30,   30,   30,   30,   30,  101,   89,
      108,  103,  103,  104,  106,  109,   30,   30,  104,  299,
       30,  110,  295,  294,   30,  293,  269,  266,   97,  264,
      192,   30,   30,   30,   30,   30,  111,  108,  160,  158,
      157,  104,  109,   30,   30,  111,  104,   30,  113,  110,
      113,   30,   31,   31,   31,   31,   31,   31,   31,   31,
       31,  112,  115,  117,  111,   31,   31,   31,   31,   31,
       31,  116,  111,   31,  120,  113,  119,  113,  112,   31,
       31,  121,   31,   31,  123,  153,  124,  125,  126,  112,

      117,  115,  152,  127,   31,   31,   31,   31,   31,  116,
      129,   31,  130,  119,  120,  112,   31,   31,  121,   31,
       31,   42,  123,  124,  125,   42,  126,  131,   42,   42,
      127,  128,  128,   42,  132,  133,   42,  135,  129,  130,
      134,  120,  137,  140,  142,   42,  147,  138,  136,   88,
       42,  139,   87,   42,  138,  131,   42,   42,  128,  128,
       42,  132,  136,   42,  133,  141,  135,  134,  143,  137,
      140,  142,   42,   43,  147,  138,  143,  136,   43,   43,
      139,  138,  144,   43,  145,   43,   43,  146,  148,  136,
       43,  149,  150,   76,  141,   43,   75,  143,   74,   73,

       72,   43,   70,  161,  143,  162,   43,   43,  164,  144,
       43,  145,   43,   43,  146,  148,  165,   43,  166,  150,
      149,  159,   43,  159,  159,  159,  159,  159,  159,  159,
      159,  161,  162,  167,  173,  164,  169,  171,  174,  174,
      176,  177,   69,  178,  165,  179,  166,  180,  181,   68,
      184,  186,  187,   66,  188,  189,  193,   65,  194,  196,
      198,  167,  173,  169,  171,  199,  174,  174,  176,  177,
      178,  200,  203,  179,  180,  207,  181,  184,  204,  186,
      187,  188,  189,  204,  193,  194,  196,  198,  209,  215,
      218,  220,  199,  222,  223,  224,  225,   64,  200,   63,

      203,   62,   61,  207,   60,  230,  204,  232,  238,  234,
      235,  204,  242,  245,   59,  209,  233,  215,  218,  220,
      222,  223,  224,  234,  225,  228,  228,  228,  228,  228,
      228,  228,  228,  230,  232,  238,  233,  234,  235,  242,
      246,  245,  248,  249,   58,  250,  252,  233,  233,  251,
      234,  253,   57,  254,  256,  260,  261,  268,  263,  268,
      267,   56,  268,  268,  233,   52,   50,  246,  271,  248,
      270,  249,  250,  252,  233,  233,  272,  251,  277,  253,
      254,  256,  260,  270,  261,  263,  265,  267,  265,  265,
      265,  265,  265,  265,  265,  265,  271,  281,  270,  283,

      284,   27,  286,  287,  272,  288,  277,  298,  300,  301,
      270,  290,  290,  290,  290,  290,  290,  290,  290,  303,
      307,  314,   25,   18,  281,   16,   15,  283,  284,  286,
      287,   12,  288,   11,  298,  300,  301,  309,  309,  309,
      309,  309,  309,  309,  309,   10,  303,  307,  314,  329,
      329,    3,  329,  329,  330,    0,  330,  330,  330,  331,
        0,  331,  331,  331,  332,    0,  332,  332,  332,  333,
      333,  335,  335,  335,  335,  335,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,

      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "trafgen_lexer.l"
/*
 * netsniff-ng - the packet sniffing beast
 * By Daniel Borkmann <daniel@netsniff-ng.org>
 * Copyright 2012 Daniel Borkmann <dborkma@tik.ee.ethz.ch>,
 * Swiss federal institute of technology (ETH Zurich)
 * Subject to the GPL, version 2.
 */
/* lex-func-prefix: yy */
#line 12 "trafgen_lexer.l"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <stdbool.h>
#include <arpa/inet.h>

#include "trafgen_parser.tab.h"
#include "xmalloc.h"
#include "built_in.h"
#include "str.h"

extern void yyerror(const char *);

static char *try_convert_shellcode(char *sstr)
{
	bool found_any = false;
	char *bstr, *ostr = sstr, *hay, *orig = sstr;
	size_t j = 0, blen, slen = strlen(sstr), tot = 0;
	const char *needle = "\\x";

	sstr++;
	slen -= 2;

	if (slen % 4 != 0)
		return orig;

	blen = slen / 4;
	hay = sstr;
	while ((hay = strstr(hay, needle)) != NULL ) {
		hay += strlen(needle) + 2;
		found_any = true;
		tot++;
	}

	if (blen != tot || !found_any)
		return orig;

	blen += 2;
	bstr = xzmalloc(blen);

	bstr[j++] = '\"';
	while (j < blen - 1)
		bstr[j++] = (uint8_t) strtoul(sstr + 2, &sstr, 16);
	bstr[j++] = '\"';

	xfree(ostr);
	return bstr;
}

#define YY_NO_INPUT 1
#line 829 "trafgen/trafgen_lexer.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 84 "trafgen_lexer.l"


#line 1044 "trafgen/trafgen_lexer.yy.c"

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 329 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 777 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 86 "trafgen_lexer.l"
{ return K_CPU; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 87 "trafgen_lexer.l"
{ return K_FILL; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 88 "trafgen_lexer.l"
{ return K_RND; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 89 "trafgen_lexer.l"
{ return K_CSUMIP; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 90 "trafgen_lexer.l"
{ return K_CSUMIP; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 91 "trafgen_lexer.l"
{ return K_CSUMIP; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 92 "trafgen_lexer.l"
{ return K_CSUMIP; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 93 "trafgen_lexer.l"
{ return K_CSUMIP; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 94 "trafgen_lexer.l"
{ return K_CSUMUDP; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 95 "trafgen_lexer.l"
{ return K_CSUMTCP; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 96 "trafgen_lexer.l"
{ return K_CSUMUDP6; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 97 "trafgen_lexer.l"
{ return K_CSUMTCP6; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 98 "trafgen_lexer.l"
{ return K_DRND; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 99 "trafgen_lexer.l"
{ return K_DINC; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 100 "trafgen_lexer.l"
{ return K_DDEC; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 101 "trafgen_lexer.l"
{ return K_SEQINC; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 102 "trafgen_lexer.l"
{ return K_SEQDEC; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 103 "trafgen_lexer.l"
{ return K_CONST8; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 104 "trafgen_lexer.l"
{ return K_CONST16; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 105 "trafgen_lexer.l"
{ return K_CONST32; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 106 "trafgen_lexer.l"
{ return K_CONST64; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 108 "trafgen_lexer.l"
{ return K_PROT; }
	YY_BREAK
/* Ethernet */
case 23:
YY_RULE_SETUP
#line 111 "trafgen_lexer.l"
{ return K_DADDR; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 112 "trafgen_lexer.l"
{ return K_SADDR; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 113 "trafgen_lexer.l"
{ return K_ETYPE; }
	YY_BREAK
/* VLAN (802.1Q & 802.1ad) */
case 26:
YY_RULE_SETUP
#line 116 "trafgen_lexer.l"
{ return K_TPID; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 117 "trafgen_lexer.l"
{ return K_TCI; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 118 "trafgen_lexer.l"
{ return K_PCP; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 119 "trafgen_lexer.l"
{ return K_DEI; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 120 "trafgen_lexer.l"
{ return K_1AD; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 121 "trafgen_lexer.l"
{ return K_1Q; }
	YY_BREAK
/* ARP */
case 32:
YY_RULE_SETUP
#line 124 "trafgen_lexer.l"
{ return K_SHA; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 125 "trafgen_lexer.l"
{ return K_SPA; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 126 "trafgen_lexer.l"
{ return K_THA; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 127 "trafgen_lexer.l"
{ return K_TPA; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 128 "trafgen_lexer.l"
{ return K_REQUEST; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 129 "trafgen_lexer.l"
{ return K_REPLY; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 130 "trafgen_lexer.l"
{ return K_OPER; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 131 "trafgen_lexer.l"
{ return K_HTYPE; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 132 "trafgen_lexer.l"
{ return K_PTYPE; }
	YY_BREAK
/* IPv4 */
case 41:
YY_RULE_SETUP
#line 135 "trafgen_lexer.l"
{ return K_IHL; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 136 "trafgen_lexer.l"
{ return K_VER; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 137 "trafgen_lexer.l"
{ return K_TTL; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 138 "trafgen_lexer.l"
{ return K_DSCP; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 139 "trafgen_lexer.l"
{ return K_ECN; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 140 "trafgen_lexer.l"
{ return K_TOS; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 141 "trafgen_lexer.l"
{ return K_LEN; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 142 "trafgen_lexer.l"
{ return K_ID; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 143 "trafgen_lexer.l"
{ return K_FLAGS; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 144 "trafgen_lexer.l"
{ return K_FRAG; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 145 "trafgen_lexer.l"
{ return K_CSUM; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 146 "trafgen_lexer.l"
{ return K_DF; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 147 "trafgen_lexer.l"
{ return K_MF; }
	YY_BREAK
/* UDP */
case 54:
YY_RULE_SETUP
#line 150 "trafgen_lexer.l"
{ return K_SPORT; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 151 "trafgen_lexer.l"
{ return K_DPORT; }
	YY_BREAK
/* TCP */
case 56:
YY_RULE_SETUP
#line 154 "trafgen_lexer.l"
{ return K_SEQ; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 155 "trafgen_lexer.l"
{ return K_ACK_SEQ; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 156 "trafgen_lexer.l"
{ return K_DOFF; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 157 "trafgen_lexer.l"
{ return K_CWR; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 158 "trafgen_lexer.l"
{ return K_ECE; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 159 "trafgen_lexer.l"
{ return K_URG; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 160 "trafgen_lexer.l"
{ return K_ACK; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 161 "trafgen_lexer.l"
{ return K_PSH; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 162 "trafgen_lexer.l"
{ return K_RST; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 163 "trafgen_lexer.l"
{ return K_SYN; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 164 "trafgen_lexer.l"
{ return K_FIN; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 165 "trafgen_lexer.l"
{ return K_WINDOW; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 166 "trafgen_lexer.l"
{ return K_URG_PTR; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 168 "trafgen_lexer.l"
{ return K_ETH; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 169 "trafgen_lexer.l"
{ return K_VLAN; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 170 "trafgen_lexer.l"
{ return K_ARP; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 171 "trafgen_lexer.l"
{ return K_IP4; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 172 "trafgen_lexer.l"
{ return K_UDP; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 173 "trafgen_lexer.l"
{ return K_TCP; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 175 "trafgen_lexer.l"
{ return '-'; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 176 "trafgen_lexer.l"
{ return '+'; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 177 "trafgen_lexer.l"
{ return '*'; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 178 "trafgen_lexer.l"
{ return '/'; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 179 "trafgen_lexer.l"
{ return '%'; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 180 "trafgen_lexer.l"
{ return '&'; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 181 "trafgen_lexer.l"
{ return '|'; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 182 "trafgen_lexer.l"
{ return '<'; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 183 "trafgen_lexer.l"
{ return '>'; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 184 "trafgen_lexer.l"
{ return '^'; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 185 "trafgen_lexer.l"
{ return '{'; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 186 "trafgen_lexer.l"
{ return '}'; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 187 "trafgen_lexer.l"
{ return '('; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 188 "trafgen_lexer.l"
{ return ')'; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 189 "trafgen_lexer.l"
{ return '['; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 190 "trafgen_lexer.l"
{ return ']'; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 191 "trafgen_lexer.l"
{ return ','; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 192 "trafgen_lexer.l"
{ return ':'; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 193 "trafgen_lexer.l"
{ return '='; }
	YY_BREAK
case 94:
/* rule 94 can match eol */
YY_RULE_SETUP
#line 195 "trafgen_lexer.l"
{ yylineno++; }
	YY_BREAK
case 95:
/* rule 95 can match eol */
YY_RULE_SETUP
#line 197 "trafgen_lexer.l"
{ yylval.str = try_convert_shellcode(xstrdup(yytext));
		  return string; }
	YY_BREAK
case 96:
/* rule 96 can match eol */
YY_RULE_SETUP
#line 200 "trafgen_lexer.l"
{ return K_WHITE; }
	YY_BREAK
case 97:
/* rule 97 can match eol */
YY_RULE_SETUP
#line 202 "trafgen_lexer.l"
{ return K_COMMENT; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 204 "trafgen_lexer.l"
{ return K_COMMENT; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 206 "trafgen_lexer.l"
{ yylval.number = strtoul(yytext + (yytext[0] == 'x' ? 1 : 0),
					  NULL, 16);
		  return number; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 210 "trafgen_lexer.l"
{ yylval.number = strtol(yytext, NULL, 10);
		  return number; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 213 "trafgen_lexer.l"
{ yylval.number = strtol(yytext + 1, NULL, 8);
		  return number; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 216 "trafgen_lexer.l"
{ yylval.number = strtol(yytext + (yytext[0] == 'b' ? 1 : 2),
					 NULL, 2);
		  return number; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 220 "trafgen_lexer.l"
{ yylval.number = (uint8_t) (*yytext);
		  return number; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 223 "trafgen_lexer.l"
{ if (str2mac(yytext, yylval.bytes, 256))
			panic("Failed to parse MAC address %s\n", yytext);
		  return mac; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 227 "trafgen_lexer.l"
{ if (inet_pton(AF_INET, yytext, &yylval.ip4_addr) != 1)
			panic("Failed to parse IPv4 address %s\n", yytext);
		  return ip4_addr; };
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 231 "trafgen_lexer.l"
{ yylval.number = strtol(yytext + 3, NULL, 16);
		  return number; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 234 "trafgen_lexer.l"
{ yylval.number = (uint8_t) (*(yytext + 1));
		  return number; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 237 "trafgen_lexer.l"
{/* NOP */}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 238 "trafgen_lexer.l"
{ printf("Unknown character '%s'", yytext);
		  yyerror("lex Unknown character"); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 241 "trafgen_lexer.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1676 "trafgen/trafgen_lexer.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 329 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 329 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 328);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 240 "trafgen_lexer.l"



